
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
  namespace: assessment
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"           
    keyvaultName: "<KEYVAULT_NAME>"        
    tenantId: "<TENANT_ID>"                
    objects: |
      array:
        - |
          objectName: app-db-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: app-api-key
          objectType: secret
          objectVersion: ""
  secretObjects:
    - secretName: app-secrets
      type: Opaque
      data:
        - objectName: app-db-password
          key: DB_PASSWORD
        - objectName: app-api-key
          key: API_KEY
